Updated the example joker mod
Steamopollys/Steamodded pull request #206
Opened 2024-07-22 15:14 UTC by someone23832

Still a few more things to add, but, mostly ready for review and editing if needed.

2024-08-04 18:32 UTC, someone23832 commented
Still waiting for someone to give an in-depth description of how the event manager works and eval_status_text, because I only know the bare basics of those. Should be good enough to include otherwise.

2024-08-05 00:31 UTC, Aurelius7309 requested changes

2024-08-05 00:31 UTC, Aurelius7309 commented on example_mods/Mods/ExampleJokersMod/ModdedVanilla.lua
> +  -- Debuffs usually call both of these functions, essentially, when a joker is debuffed, it's simply removed from your jokers, except for the fact that it takes up a slot.
These functions are duplicates; `config.extra.d_size` and `h_size` apply these automatically. So this is actually oversaturated Merry Andy

2024-08-05 15:35 UTC, someone23832 commented on example_mods/Mods/ExampleJokersMod/ModdedVanilla.lua
> +  -- Debuffs usually call both of these functions, essentially, when a joker is debuffed, it's simply removed from your jokers, except for the fact that it takes up a slot.
Really? I had no idea, but I did want to specifically showcase `add_to_deck` and `remove_from_deck` here, just changing them to `hand_size` and `discard_size` should fix this, right? Maybe I'll also add in a footnote, are there any other config values that automatically apply things like this?

2024-08-12 14:16 UTC, merged